baseURL = "http://blog.keendly.com/"
languageCode = "en-us"
title = "Keendly blog"
theme = "beautifulhugo"
googleAnalytics = "UA-76042310-3"
disqusShortname = "keendly"

[Author]
  name = "Keendly"
  URL = "https://keendly.com"
  email = "contact@keendly.com"
  facebook = "KeendlyApp"
#  github = "username"
  twitter = "KeendlyApp"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1
